### ISSUE TITLE
Linecount comparison is not correct

### ISSUE THREAD

**Issue by HarshSharma12** [thundercomb/poetrydb#15]
If I query the following URL 

http://poetrydb.org/linecount/5

then the output contains poems with the number of lines where 5 is encountered in linecount at any place. 

To clarify, 
For the above url, the output will contain poems with linecount as 25, 50, 105, 5, 15, etc. 

If you specify it as http://poetrydb.org/linecount/10 it will return poems with linecount as 103, 105, 10, 100, etc.

So, basically there is a string.contains comparison that is taking place instead of a string.equals comparison.

**Comment by thundercomb** [comment]
Hi @HarshSharma12 

Yes that is the correct behaviour at this moment. The reason is that, as you say, it is a substring search. This is to keep the behaviour and expectation in line with the other fields (author, etc.) that are also strings.

The correct way to therefore specify the specific linecount is to use the ":abs" (absolute) modifier. For example observe the difference between the following two queries:

http://poetrydb.org/author,linecount/Alexander%20Pope;16/all.text

and

http://poetrydb.org/author,linecount/Alexander%20Pope;16:abs/all.text

Hope that helps!

**Comment by thundercomb** [comment]
Hi @HarshSharma12 

After reviewing the linecount functionality it seemed to me that, as per your suggestion, most people would see `linecount` as a numeric input field and therefore an absolute linecount would be the expected default. 

In line with this a change has now been made and it is no longer necessary to use the `:abs` qualifier to obtain the exact number of lines with the `linecount` search field.

This should hopefully make for a more intuitive use of the `linecount` input field.

**Comment by HarshSharma12** [comment]
Great. Thanks for the update :)
