### ISSUE TITLE
Including poetry

### ISSUE THREAD

**Issue by peterbsmyth** [thundercomb/poetrydb#18]
I was building an api for my poetry. Is it ok to collaborate so I can include my poetry in poetry dB?

**Comment by thundercomb** [comment]
Hi @peterbsmith2 - thank you for offering to collaborate on the poetry data. I currently manage data held in the backend mongodb directly (rather than via the code repo). However I am open to suggestions and if you could point me to the data I would be happy to review and work out a way for us to include it.

One of the main conditions is that the source poems should themselves be 'open source'. In other words, they should be in the public domain and not copyrighted. (For this reason the bulk of PoetryDB's available poetry is classical poetry.)

Thanks and look forward to hearing from you.

**Comment by thundercomb** [comment]
Closing this due to no further activity.
