### ISSUE TITLE
Parentheses in poem title

### ISSUE THREAD

**Issue by canzhiye** [thundercomb/poetrydb#2]
I'm trying to grab "Song (Go And Catch A Falling Star)" by John Donne via requests in python, but I think the url is not being encoded properly. If I paste "http://poetrydb.org/title/Song (Go And Catch A Falling Star)/lines.json" into the address bar, I get a 404. How do I properly format this request?

**Comment by thundercomb** [comment]
Hi Canzhi, thanks for raising the issue - escaping the brackets gives the desired result:

`http://poetrydb.org/title/Song \(Go And Catch A Falling Star\)/lines.json`

I'll leave the issue open for the moment to evaluate if this behaviour should change.

**Comment by thundercomb** [comment]
Note that browsers tend to replace backslashes with forward slashes. On the command line something like the following probably works fine:

`wget "http://poetrydb.org/title/Song \(Go And Catch A Falling Star\)/lines.json" -O -`

However in the browser use the encoding `%5C` instead of the backslash:

`http://poetrydb.org/title/Song %5C(Go And Catch A Falling Star%5C)/lines.json`
