### ISSUE TITLE
503 Status Error - Application Error on Heroku

### ISSUE THREAD

**Issue by Awesomeplayer165** [thundercomb/poetrydb#47]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/70717139/197848884-2aea46f6-dfa1-4e6e-85af-b447ab52fe70.png">
Receiving an Application Error 503 - Service Unavailable. Is the API down?

**Comment by thompson-dean** [comment]
Any updates on this?

**Comment by Awesomeplayer165** [comment]
For me, it's still 503 with the same Heroku error page

**Comment by Amro15** [comment]
same issue here

**Comment by thundercomb** [comment]
Sorry folks, just noticed this. 
The app was up but it turns out the free dynos on Heroku had been exhausted for October, and then the app is made inaccessible. I also noticed that Heroku is planning to end-of-life free dynos as of 22 November. 
I've therefore taken the decision to upgrade to a paid tier to ensure continuity.

Apologies for the inconvenience, and thanks for your patience. PoetryDB is back online.

**Comment by Awesomeplayer165** [comment]
Great, thank you so much!

**Comment by thundercomb** [comment]
You're welcome.

**Comment by thompson-dean** [comment]
really appreciate your work @thundercomb ! Thank you!
